### PR TITLE
Adds logo to the menu sidebar

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
Our logo has been missing from our menu sidebar for quite a while. This PR adds the logo to the MenuSidebar component.

## Related issue number (if any)
Resolves: https://linear.app/aqueducthq/issue/ENG-1225/add-logo-to-menu-sidebar-on-the-ui

Screenshot:
image

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
Thoughts on making the logo the full width of the menu bar vs. keeping it in the top left?

**Comment by likawind** [comment]
Yeah it looks a bit squeezed to me esp. that our menu items occupies wider space

**Comment by agiron123** [comment]
Agreed that it's a little bit awkward. Going to try making this full width as well. I'll also probably need to re-crop the logo (and will do the same for our other variants) in a tool like Photoshop to be more precise. Did this one in Figma and I'm not so happy with how it turned out.

**Comment by agiron123** [comment]
@vsreekanti @likawind Photoshopped the logo some more, here's a screenshot of it now, (added some padding to line up with the Avatar below it

image

**Comment by agiron123** [comment]
Going to try a full width version so we can compare the two side by side now

**Comment by vsreekanti** [comment]
Yeah, this is good. I wonder if we shouldn't just make it 100% width? Also, how does this interact with our planned menubar redesign? (i.e., is it worth spending more time on if we're going to change the dimension of the menu bar soon anyway?)

**Comment by agiron123** [comment]
Full width version is here:
image

**Comment by agiron123** [comment]
This will be a stopgap for a bit, but still worth doing as the new menu bar is going to be a couple days work

**Comment by vsreekanti** [comment]
IMO, the full version looks quite a bit better. I'd go with that.

**Comment by agiron123** [comment]
@vsreekanti sounds good, we'll go with the full version.

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
