### PR TITLE
Refines existing and adds new example notebooks

### PR DESCRIPTION
**Pull request by vsreekanti**
## Describe your changes and why you are making these changes

This PR adds 3 new example notebooks and refines a bunch of the existing notebooks by adding better documentation, adding more high-level explanation of what's happening, and fixing typos. This PR also runs `black` on all of the notebooks. 

@saurav-c @cw75 @likawind, this PR also adds 2 new datasets, which will require updating the demo DB. What's the right way to go about doing that?

## Related issue number (if any)

N/A

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [N/A] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A] If this is a new feature, I have added unit tests and integration tests.
- [N/A] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [N/A] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
I know there's a lot of files here, so if folks are curious, I'm happy to jump on a call and go through the changes I made generally.

**Review by likawind — COMMENTED** [review]
https://github.com/aqueducthq/aqueduct/tree/main/src/resources/demo_db/sqlite we can add new tables here. @cw75 knows these better but my understanding is we need to add `<table>.tsv`, `<table>.sql` and lines in `init_db.sh`. Then we could run `init_db.sh` to generate the 'compiled' db.

**Comment by cw75** [comment]
@vsreekanti I think we can add logic to our CLI that 1) check if the new tables exist in the user's `demo.db`, and if not 2) run sql commands to create the tables and load data into the db.

**Comment by saurav-c** [comment]
@vsreekanti Is there anything we can do to get this merged?

**Comment by cw75** [comment]
@vsreekanti ok I verified that all notebooks are working. The only issue I found is that when writing to the demo db in the wine workflow and the house price workflow, it errored with "sqlite3.OperationalError: too many SQL variables". We should look into what's going on.

**Comment by cw75** [comment]
@vsreekanti I think this PR is ready to be merged.

**Comment by vsreekanti** [comment]
@cw75, cool, feel free to go ahead and merge this whenever you're ready!

**Pull request merged**
