### PR TITLE
ENG-931 make small tables take up full width of side drawer

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR renders tables with few columns as full width in the Side Drawer.

i.e. a table with just one column now takes up the whole width of the Side Drawer instead of it being really thin.

## Related issue number (if any)
ENG-931

## Loom Demo:
https://www.loom.com/share/bd71c827ac814ca0b129b69a808c26c9

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@agiron123, when you show the single column, it appears there's still a horizontal scroll. Is that an issue with the hardcoded width or the padding?

**Comment by agiron123** [comment]
> @agiron123, when you show the single column, it appears there's still a horizontal scroll. Is that an issue with the hardcoded width or the padding?

@vsreekanti good catch, yeah I believe it's an issue of both hard coded width and some padding. I've gone ahead and fixed this.

You can find an updated loom demo here:
https://www.loom.com/share/ec5ffa2b658a4763aa8c5261cae38276

**Comment by vsreekanti** [comment]
Awesome, @agiron123! Once we replace the drawers with the details pages, is this view still going to be used?

**Review by vsreekanti — APPROVED** [review]

**Comment by agiron123** [comment]
> Awesome, @agiron123! Once we replace the drawers with the details pages, is this view still going to be used?

@vsreekanti good question. I'm not really sure to be honest. New designs call for the paginated table instead, but it's still nice to have this change around while we make our transition.

**Pull request merged**
