### PR TITLE
Make password optional for the Postgres integration

### PR DESCRIPTION
**Pull request by eunice-chan**
## Describe your changes and why you are making these changes
`postgresql://{username}@{host}:{port}/{database}` if no password else `postgresql://{username}:{password}@{host}:{port}/{database}`
Details about connection uris schema: [connection uris](https://www.prisma.io/dataguide/postgresql/short-guides/connection-uris)

## Testing
Was able to create an integration with no password. 

Output:
```
INFO[0035] Job discover-operator-b74341d0-cfb7-4463-9fe8-6fdafcef5436 Stdout:
 Job Spec: 
{
    "type": "discover",
    "name": "discover-operator-b74341d0-cfb7-4463-9fe8-6fdafcef5436",
    "storage_config": {
        "type": "file",
        "file_config": {
            "directory": "/Users/eunice/.aqueduct/server/storage"
        }
    },
    "metadata_path": "list-tables-metadata-c8c0c05c-fe62-11ec-8da9-16d00539493d",
    "connector_name": "Postgres",
    "connector_config": {
        "conf": {
            "database": "test",
            "host": "3.142.105.48",
            "password": "",
            "port": "5432",
            "username": "postgres"
        }
    },
    "output_content_path": "list-tables-result-c8c0c05c-fe62-11ec-8da9-16d00539493d"
}
Started JobType.DISCOVER job: discover-operator-b74341d0-cfb7-4463-9fe8-6fdafcef5436
writing to file: list-tables-result-c8c0c05c-fe62-11ec-8da9-16d00539493d
writing to file: list-tables-metadata-c8c0c05c-fe62-11ec-8da9-16d00539493d
 
 Stderr: 
 
```

## Related issue number (if any)
ENG-1330

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A] If this is a new feature, I have added unit tests and integration tests.
- [N/A] I have run the integration tests locally and they are passing.
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by saurav-c — APPROVED** [review]
LGTM Do you mind adding a short demo video of the ui with these changes for connecting a new Postgres integration

**Comment by eunice-chan** [comment]
@vsreekanti Just tested. Seems to work. Let me know if there's anything else I should check!

Details of what I specifically checked below:

Added a table with these values: 
image

Ran this in Python in interactive shell mode:
```import aqueduct
client = aqueduct.Client(
    "1CZR2J96NKXL4UWEO57PID03GAVTHB8Q",
    "http://localhost:8080"
)
integration = client.integration(name="postgres/123")
table = integration.sql(query="SELECT * FROM recipes;")
table.get()
client.publish_flow(name="recipes", artifacts=[table])
```

`table.get()` returns what is expected.

```
>>> table.get()
   recipe_id     recipe_name
0          1           Tacos
1          2     Tomato Soup
2          3  Grilled Cheese
```
The workflow displays correctly on the UI:
image
Pressed `Run Workflow` and it still works:
image

**Comment by eunice-chan** [comment]
> LGTM Do you mind adding a short demo video of the ui with these changes for connecting a new Postgres integration
Hi Saurav! the UI shouldn't change much--the only difference is that having a value in the password field is not required to make the confirm button enabled and there is no asterisk next to the password. I'll record post a demo shortly. 
image

**Comment by eunice-chan** [comment]
As you can see in this video, the password is not required for the config to be considered complete.

https://user-images.githubusercontent.com/30596854/178045845-763d3ee6-0d99-4cd4-8711-85cd3155f568.mov

**Pull request merged**
