### PR TITLE
Eng 2125 differentiate key values better

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR better differentiates the key and value pairs for the metrics list item.

Also changed the show more text to be a little less bold.

## Related issue number (if any)
ENG-2125

## Loom demo (if any)
https://www.loom.com/share/f72ed7e8df29432d92a7b8bf7238c672

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by eunice-chan** [comment]
I like it! The "No metrics." look a little strange to me--what if we give the No checks/metrics the same styling as the other cells e.g. Last Run, Engine.

Whatever is the final design, I think the changes should also be done in the metrics and checks section of the details page (that is, updating `src/ui/common/src/components/tables/OperatorExecStateTable.tsx`).

**Comment by agiron123** [comment]
@eunice-chan here's the No metrics. text put back to what it was before:

image

**Comment by agiron123** [comment]
@eunice-chan good suggestion on updating check/metric history, here's what this looks like:
image

**Comment by eunice-chan** [comment]
@agiron123 Looks good!

The metrics on the Artifact Details page look different compared to the checks. Can you update the title to have a heavier weight?
Screen Shot 2023-01-11 at 10 59 39 AM

**Comment by agiron123** [comment]
@eunice-chan Here is an updated screenshot of artifact details:
image

**Review by eunice-chan — APPROVED** [review]

**Pull request merged**
