### PR TITLE
ENG 2408 add notification configurations to account page

### PR DESCRIPTION
**Pull request by likawind**
## Describe your changes and why you are making these changes
This PR adds a notification section to accounts page. We provides similar experience to individual integration settings such that user can enable / disable notification to all workflows, and select levels.

We allow editing these settings in-place and shows 'save' / 'cancel' buttons if any change is detected. We properly handle the async API call to load / update integrations by:
* when integrations are loading / failed to load, show circular progress or error alert respectively
* when updating integrations, disable save button until the call returns.
* show error / success badge depending on the update call status
* load integration list after editing is done (regardless of success / fail)
We also removed the large 'account overview' title  to be consistent with other pages.

## Related issue number (if any)
ENG-2408

## Loom demo (if any)
https://www.loom.com/share/1fa9065dd5d941788c388e32bbfec56b

## Checklist before requesting a review
- [ ] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ ] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by likawind** [comment]
@vsreekanti @agiron123  I'm not a big fan of how we put notifications in a list here but can't come up with anything better:

Screenshot 2023-02-10 at 5 05 44 PM

**Comment by likawind** [comment]
Added a helper text:
Screenshot 2023-02-10 at 5 09 50 PM

**Comment by vsreekanti** [comment]
Thanks, @likawind! The functionality here looks good, but a few things on the layout.
* I think the grey boxes take up a lot of visual space, so let's remove them and just add a divider between each notification integration. (I believe MUI has a `Divider` component.)
* Let's make the name of the integration slightly bigger — maybe an `h6`?
* Let's separate out the apply to all configuration from the error level configuration. Perhaps we could do something like this: 

## Notifications
Configure how your notification(s) apply to all new workflows. You can override these settings in each workflow's individual settings page. *Note there's a typo in the apostrophe escape in the current UI.*

- [ ] my_gmail 
    *my_gmail notifications will not be configured for new workflows by default.*
- [x] my_slack
    - [x] Error
    - [ ] Warning
    - [ ] Success

**Comment by likawind** [comment]
Thanks! @vsreekanti , with 3, do you still feel the integration size should be larger than options?

**Comment by likawind** [comment]
@vsreekanti @agiron123 with most feedbacks putting together:
Account page:
Screenshot 2023-02-13 at 4 13 49 PM

Workflow settings page:
Screenshot 2023-02-13 at 4 21 48 PM


Notification (integration) settings / creation page, when enabled (I feel it's slightly overwhelming in contents, but gives good information separation on enable / disable vs level selection):
Screenshot 2023-02-13 at 4 16 17 PM

Notification (integration) settings / creation page, when disabled:
Screenshot 2023-02-13 at 4 16 33 PM

**Comment by likawind** [comment]
Merging to base and run additional tests for the cut. Plz keep commenting if you have suggestions, will fix after release

**Pull request merged**
