### PR TITLE
ENG-2130 Remove Settings Account Popover

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR removes the Account popover in the navigation bar that appeared when users clicked the settings gear.
Users can now navigate to the Account page simply by clicking the settings gear.

## Related issue number (if any)
ENG-2130

## Loom demo (if any)
https://www.loom.com/share/de15a7714f1c4570ab48236b16f18844

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by agiron123** [comment]
@vsreekanti using the settings gear here, should I replace with the user icon instead?

I think that might be a nice touch and would remove the confusion between the two settings gears that appeared close to one another.

**Comment by agiron123** [comment]
would just be a matter of setting the icon to ```faCircleUser```

**Comment by vsreekanti** [comment]
Hm, I don't think account is really the right metaphor anymore. Maybe we could use a sliders icon like [this](https://fontawesome.com/icons/sliders?s=solid&f=classic)?

**Comment by agiron123** [comment]
@vsreekanti Icon should be updated to sliders now:
image

**Review by vsreekanti — APPROVED** [review]
:shipit:

**Pull request merged**
