### PR TITLE
Eng 1655 redirect user to 404 page if they access invalid url

### PR DESCRIPTION
**Pull request by eunice-chan**
## Describe your changes and why you are making these changes
If the url does not exist or redirected to the /404 page in the existing site, will now go to a functioning 404 page.

## Related issue number (if any)
Eng 1655

## Loom demo (if any)
If not logged in
not_logged_in_404

If logged in
logged_in_404

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [n/a] If this is a new feature, I have added unit tests and integration tests.
- [n/a] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by likawind** [comment]
This is neat! I love the helper message!

I'm not sure if we should use 'something went wrong' as often it could be expected the page simply doesn't exist. I would consider using 'The page you requested does not exist' instead. I'm curious how others think @agiron123 @vsreekanti .

**Comment by vsreekanti** [comment]
I agree with Wei's suggestion. Maybe a mix of the two: "Something went wrong — we can't find the page you're looking for." 

Also, small typo in the second line. It should be "you *can* make a post".

**Comment by eunice-chan** [comment]
Thanks for the feedback. Updated messaging:

image

**Comment by vsreekanti** [comment]
Thanks, @eunice-chan! Tiny, tiny nit, but can we center justify both blocks of text?

**Comment by eunice-chan** [comment]
@vsreekanti Updated:
image

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
