### PR TITLE
ENG-1860: Parameter Status Bar Label and add Parameter Icon

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR gives parameters label in status bar output. Adds icon and node type to use for rendering parameters should we choose to render them in the future.

## Related issue number (if any)
ENG-1860

## Loom demo (if any)

Updated loom demo:
https://www.loom.com/share/f6d8e0e722084134bd80641fe324591d

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by kenxu95 — COMMENTED** [review]
Just based on the demo, some questions:
- In the failed case, the label still reads "Table Artifact", even though the type of the parameter was definitely not a table. Any idea why this is? It seems like we're hardcoding this somewhere.
- Long-term, I'd really like to get rid of the "parameter operator" idea from any of the user surfaces. It probably doesn't have to be a part of this release, but can we make a future task for it? This would involve cutting the link to the parameter operator's page, as well as replacing the parameter card label "Parameter Operator" with just "Parameter". cc: @vsreekanti for confirmation on this direction.

**Comment by vsreekanti** [comment]
@agiron123, what's the status of this PR?

**Comment by agiron123** [comment]
> @agiron123, what's the status of this PR?

Just need to resolve Ken's feedback here and we should be good to go. Sorry this one slipped through the cracks a bit. Will get taken care of today.

**Comment by agiron123** [comment]
@kenxu95 updated demo should be here:
https://www.loom.com/share/f6d8e0e722084134bd80641fe324591d

**Review by likawind — APPROVED** [review]
We removed parameter operators from 'generated by' section as a part of 1859: https://github.com/aqueducthq/aqueduct/pull/649 . Could you try to rebase and confirm if other parts like error messages still works? Approving as I believe that's the case.

**Review by kenxu95 — APPROVED** [review]
Two nits that I think you can get in pretty easily?
1) I still see a "$" preceding "nationality" here. Can we remove that? 
image

2) Would it be too hard to just call this "Parameter" instead of "Parameter Operator"? 
image

**Comment by agiron123** [comment]
eng-1860
^ updated screenshot

**Pull request merged**
