### PR TITLE
[3/3] Handles readonly fields and provide workflow information in integration dialog

### PR DESCRIPTION
**Pull request by likawind**
## Describe your changes and why you are making these changes
This PR enhances integration dialog:
* Note: this PR is not completed. We only updated snowflake dialog as an example. Once we agreed on UX I will update the PR with other dialogs
* during creation, add warnings for read-only fields
* during edit, disable read-only fields with helper text. Adds an info to inform user that existing workflows will be affected.

## Related issue number (if any)
ENG-170

## Checklist before requesting a review
[Demo](https://www.loom.com/share/84b456e0153d4cbfaa1efae99e87a7e6)
When there's workflow associated:
Screen Shot 2022-08-09 at 5 15 43 PM

- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] (Integration test will be added in follow-ups tracked by ENG-1520) If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@likawind, the Loom link you shared doesn't seem to work. It might be because our account deletion is in process. For now, can you rerecord using Quicktime?

**Comment by likawind** [comment]
@vsreekanti @agiron123 sorry for the delay but the demo is updated!

**Comment by vsreekanti** [comment]
@likawind, nice work! A few things:
* A few English nits: 
  * It should be "You cannot edit this field." rather than "You couldn't".
  * Rather than "We have trouble connecting to the integration.", it should be "We were unable to connect to <integration_name>."
  * When there's a workflow for this integration, the text should read, "Changing this integration will automatically update N workflow(s)." 
* Let's make the options drop down menu right aligned with the button rather than left-aligned.
* Let's not make the warning text yellow -- it's quite distracting. I would just put it on the same line as the descriptor text and maybe put it in italics for emphasis.

**Comment by likawind** [comment]
@vsreekanti here are updated screenshots based on your suggestions:
option alignments:
Screen Shot 2022-08-23 at 5 13 24 PM
english (couldn't -> cannot)
Screen Shot 2022-08-23 at 6 00 11 PM

warning color:
Screen Shot 2022-08-23 at 5 18 28 PM

**Comment by vsreekanti** [comment]
This is perfect, @likawind -- :shipit:!

**Review by agiron123 — APPROVED** [review]
Looks good on my end. 

Agree with @vsreekanti on the copy changes. Once those go in, should be good to go.

**Pull request merged**
