### PR TITLE
ENG-2573: Updates node text size and the initial viewport of react flow canvas.

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR updates the viewport starting x,y,zoom of ReactFlow canvas as well as makes the text size of DAG nodes larger.

## Related issue number (if any)
N/A (will create soon)

## Loom demo (if any)
https://www.loom.com/share/dff9a948609441aebeb1bea6443a2876

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by likawind — APPROVED** [review]
Code LGTM!

**Comment by vsreekanti** [comment]
@agiron123, quick question about this — we do the refresh, but we don't actually seem to update the state on the UI in this demo. i.e., we rename from `succeed_complex_renamed` to `succeed_complex`, but once you do the reload, the breadcrumb and the header of the workflow page both still have `succeed_complex_renamed` on them. Is that intentional? It seems quite confusing to me from a UX perspective.

**Comment by vsreekanti** [comment]
@agiron123, the node issue was resolved by my other PR, and I bet it's going to cause some annoying merge conflict issue. 

As for the starting point of the ReactFlow viewport, I'm not sure I like the idea of starting with the DAG cutoff. We might have to do this for extremely large DAGs, but for normal-sized DAGs like the ones we have in our tests, I would very much like to show the whole DAG on-load when possible. Let's discuss further before finalizing this.

**Comment by agiron123** [comment]
> @agiron123, the node issue was resolved by my other PR, and I bet it's going to cause some annoying merge conflict issue.
> 
> As for the starting point of the ReactFlow viewport, I'm not sure I like the idea of starting with the DAG cutoff. We might have to do this for extremely large DAGs, but for normal-sized DAGs like the ones we have in our tests, I would very much like to show the whole DAG on-load when possible. Let's discuss further before finalizing this.

@vsreekanti Sounds good. I'm just going to close this PR.

**Pull request closed without merging**
