### PR TITLE
Remove upstream parameter operator when displaying parameter artifacts

### PR DESCRIPTION
**Pull request by likawind**
## Describe your changes and why you are making these changes
This PR hides parameter operator when displaying parameter artifacts.

## Related issue number (if any)
ENG-1859

## Loom demo (if any)
Screen Shot 2022-10-26 at 5 30 47 PM

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ ] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
If the artifact or operator summary lists are empty, can we just return null?

**Comment by likawind** [comment]
@vsreekanti what do you mean by return null? I agree it's a little weird that we show a 'generated by' where the section is blank. Should we show some message like 'no operator generates this artifact'?

**Comment by vsreekanti** [comment]
If you `return null` from a React component nothing is rendered on the screen in that location, so if we detect that the list is empty, returning null will just make the element go away.

**Comment by likawind** [comment]
I see, so we just remove the 'generated by' altogether? Do you think if the 'consumed by' should still be right-aligned in this case?

**Comment by vsreekanti** [comment]
No, it can be left-aligned!

**Comment by likawind** [comment]
@vsreekanti fixed:
Screen Shot 2022-10-27 at 11 34 52 AM

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
