### PR TITLE
Set up demo codespace

### PR DESCRIPTION
**Pull request by likawind**
## Describe your changes and why you are making these changes
This PR adds necessary change to deploy a demo codespace that consists of all example notebooks. User can browse these workflows in UI and also play around with the notebooks. We also added a readme to instruct the user to do so.

Caveats:
* I need to remove `sentiment` as it requires torch. The resulting img will be 5G and it crashes container build (I believe the dkr pull exceed the size limit).
* Some workflows are deployed with a schedule. This means they will be triggered at codespace start time as the server will treat these runs as missing

## Related issue number (if any)
ENG-2546

## Loom demo (if any)
This link should work: https://github.com/codespaces/new?hide_repo_select=true&ref=demo_codespace&repo=496844646

## Checklist before requesting a review
- [ ] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [ ] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@likawind, a couple questions: 
1. Will we need to keep this branch up to date on every release? or only when the demo DB changes? 
2. Can we turn off the schedule? Seems unnecessary for this.

**Comment by likawind** [comment]
@vsreekanti yes, we should keep it up to date. I will update release script / checklist once the PR is pushed.

The thing is we run the entire example notebooks to publish them in the codespace, so the schedule follows whatever in these notebooks.

I'm not sure if we should change the notebooks since they serve for other purposes. The easiest thing to do is to add a server flag so that we skip backfilling skipped workflows on start time?

**Comment by vsreekanti** [comment]
I'd be okay with removing the schedules from the example notebooks. If people are running those, there's no reason that they would want it to actually update every day. 🙂

**Comment by likawind** [comment]
@vsreekanti updated all schedules, this PR should be good to go

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
