### PR TITLE
Show which engine the workflow is running on on the UI's workflow page

### PR DESCRIPTION
**Pull request by Fanjia-Yan**
## Describe your changes and why you are making these changes
This PR adds display to what engine the workflow is running on in two locations, the workflow browsing page and the workflow detail page. 
## Related issue number (if any)
https://linear.app/aqueducthq/issue/ENG-1812/show-which-engine-the-workflow-is-running-on-on-the-uis-workflow-page
## Loom demo (if any)
Screen Shot 2022-10-12 at 1 14 41 PM
Screen Shot 2022-10-12 at 1 14 31 PM

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by cw75 — APPROVED** [review]
LGTM!

**Comment by agiron123** [comment]
Nice work! I just want to confirm that things stack like the other elements in the workflow header when you make your browser window smaller. Does that happen?

**Review by agiron123 — APPROVED** [review]
LGTM

**Review by agiron123 — CHANGES_REQUESTED** [review]
Shoot, I should have checked what branch you are making this PR to. Could you make these changes to ui-redesign instead of main?

There's quite a bit changed in our UI, so we want to make sure that this goes into the latest workflow header.

**Comment by Fanjia-Yan** [comment]
> Nice work! I just want to confirm that things stack like the other elements in the workflow header when you make your browser window smaller. Does that happen?

@agiron123 I was not exactly familiar with the problem of making the browser smaller so I make a video, let me know if that's normal 
https://www.loom.com/share/82503b7bd85747f5a336a890ee290664

**Comment by Fanjia-Yan** [comment]
> 

Yeah, will do that now!

**Comment by Fanjia-Yan** [comment]
Screen Shot 2022-10-13 at 4 48 22 PM
Screen Shot 2022-10-13 at 4 49 18 PM
Updated UI PR on ui-redesign branch

**Pull request merged**
