### PR TITLE
Allow users to create operators from existing functions

### PR DESCRIPTION
**Pull request by Fanjia-Yan**
## Describe your changes and why you are making these changes
In this PR, I added a method call `to_operator()` in SDK. When we have an existing python function, we can call on `to_operator(func)` to covert it to Aqueduct Operator instead of redefining using `@op`. The integration test checks whether there is any difference between `@op` defined operator and `to_operator` defined operator 
Screen Shot 2022-07-25 at 10 21 22 AM
Screen Shot 2022-07-25 at 10 50 17 AM

## Update 1.0
After Wei's PR on enabling passing in imported function, Now the to_operator() can takes in locally defined function and imported function and convert them to an Aqueduct operator for use. I have also added an integration test to make sure it is working. 

## Related issue number (if any)
Eng 1318
https://linear.app/aqueducthq/issue/ENG-1318/allow-users-to-create-operators-from-existing-functions
## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@Fanjia-Yan, can you test if this works with imported functions? i.e., I have a file called `test.py` with a function `test_fn`, and I want to do `import test_fn; to_operator(test_fn)` and then use it?

**Comment by Fanjia-Yan** [comment]
> @Fanjia-Yan, can you test if this works with imported functions? i.e., I have a file called `test.py` with a function `test_fn`, and I want to do `import test_fn; to_operator(test_fn)` and then use it?

It seems like the imported function does not work. I am looking into how to enable imported function be converted to an operator.

**Comment by vsreekanti** [comment]
This might be because of the package issue that @cw75 was talking about last week. What is the error you're getting @Fanjia-Yan?

**Comment by Fanjia-Yan** [comment]
> This might be because of the package issue that @cw75 was talking about last week. What is the error you're getting @Fanjia-Yan?
Let me try to reproduce it on jupyter notebook
Screen Shot 2022-07-25 at 7 27 22 PM

**Comment by Fanjia-Yan** [comment]
> > This might be because of the package issue that @cw75 was talking about last week. What is the error you're getting @Fanjia-Yan?
> > Let me try to reproduce it on jupyter notebook
> > Screen Shot 2022-07-25 at 7 27 22 PM

This is the one I got from integration test

**Comment by Fanjia-Yan** [comment]
It seems like the function from other file is not successfully recorded by the DAG and when the aqueduct executor parse the function file, it fails.

**Comment by vsreekanti** [comment]
Hm, the logs seem incomplete. I believe this is because when you call `cp.load` on the function, it's not able to find the package. Can you check the server logs to see what the full error message is?

**Comment by Fanjia-Yan** [comment]
> Hm, the logs seem incomplete. I believe this is because when you call `cp.load` on the function, it's not able to find the package. Can you check the server logs to see what the full error message is?


The Complete Server log from terminal:

ERRO[0961] Unexpected error occurred while executing job function-operator-3b5cc6fe-e62b-4de2-b27f-8c30f7e8befd: exit status 1. Stdout: 
 Job Spec: 
{"name": "function-operator-3b5cc6fe-e62b-4de2-b27f-8c30f7e8befd", "type": "function", "storage_config": {"type": "file", "file_config": {"directory": "/home/ubuntu/.aqueduct/server/storage"}, "s3_config": null}, "metadata_path": "7dc6c796-721a-4d2c-894f-8ee2d040de3e", "function_path": "operator-1b303499-99d7-4966-b4e3-e6b644772ecc", "function_extract_path": "/home/ubuntu/.aqueduct/server/storage/operators/735bd249-a846-4398-ae17-aeedf5205a19", "entry_point_file": "model.py", "entry_point_class": "Function", "entry_point_method": "predict", "custom_args": "", "input_content_paths": ["6a523d19-89da-4515-924e-a65eb02a44a8"], "input_metadata_paths": ["46517a93-91b5-4bf9-b68c-6d7f3d4925e0"], "output_content_paths": ["e20bd60c-610c-4008-a176-59a15478baad"], "output_metadata_paths": ["cb4610f1-e080-49cd-a046-993ccd448d9a"], "input_artifact_types": ["table"], "output_artifact_types": ["table"]}
reading from file: /home/ubuntu/.aqueduct/server/storage/operator-1b303499-99d7-4966-b4e3-e6b644772ecc

----------------

A bunch of requirement already satisfied statement 

----------------

Invoking the function...
Failed with system error. Full Logs:
{"user_logs": {"stdout": "", "stderr": ""}, "status": "failed", "failure_type": 1, "error": {"tip": "Sorry, we've run into an unexpected error! Please create bug report in github: https://github.com/aqueducthq/aqueduct/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D . We will get back to you as soon as we can.", "context": "  File \"/home/ubuntu/.local/lib/python3.8/site-packages/aqueduct_executor/operators/function_executor/execute_function.py\", line 119, in run\n    results, system_metadata = _execute_function(spec, inputs, exec_state)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/aqueduct_executor/operators/function_executor/execute_function.py\", line 82, in _execute_function\n    invoke = _import_invoke_method(spec)\n  File \"/home/ubuntu/.local/lib/python3.8/site-packages/aqueduct_executor/operators/function_executor/execute_function.py\", line 61, in _import_invoke_method\n    function = fn_class()\n  File \"/home/ubuntu/.aqueduct/server/storage/operators/735bd249-a846-4398-ae17-aeedf5205a19/op/model.py\", line 7, in __init__\n    self.func = cp.load(f)\n"}}
writing to file: /home/ubuntu/.aqueduct/server/storage/7dc6c796-721a-4d2c-894f-8ee2d040de3e
 
 Stderr: 
  
ERRO[0961] Unable to clean up storage file with key: cb4610f1-e080-49cd-a046-993ccd448d9a. remove /home/ubuntu/.aqueduct/server/storage/cb4610f1-e080-49cd-a046-993ccd448d9a: no such file or directory. 
ERRO[0961] Unable to clean up storage file with key: e20bd60c-610c-4008-a176-59a15478baad. remove /home/ubuntu/.aqueduct/server/storage/e20bd60c-610c-4008-a176-59a15478baad: no such file or directory.

**Comment by vsreekanti** [comment]
That's super weird. I wonder why we're cutting this off -- it doesn't actually say *what* the error is. @likawind @cw75 are there any other places we could check for logs?

**Comment by likawind** [comment]
I think the logs are off because it happens in a really unusual place - we use cloudpickle to load the pickled user function to our wrapper, and then this wrapper object get dynamically imported. I feel either we have something wrong with fetching the trace, or the dynamic import part might cut some stack trace for us

**Comment by likawind** [comment]
https://linear.app/aqueducthq/issue/ENG-1445/investigate-why-traces-are-off-for-dynamic-imports

**Comment by likawind** [comment]
@Fanjia-Yan we will look at this together but there are also thing you could try out:
* try pull and update to the latest version. This shouldn't fix your issue but would bring us to the same page on where to look at.
* try to manually unzip the operator, import the object, and initialize it as what's been done in `_import_invoke_method`. Hopefully this would reproduce the bug

**Comment by Fanjia-Yan** [comment]
## Update 1.0
After Wei's PR on enabling passing in imported function, Now the to_operator() can takes in locally defined function and imported function and convert them to an Aqueduct operator for use. I have also added an integration test to make sure it is working.

**Comment by vsreekanti** [comment]
@Fanjia-Yan, thanks for pushing through on this. As of your latest update, it sounds like the example test case I mentioned previously work? If so, I think this should be good to go from a product perspective! 

I'll let someone who knows the SDK codebase better than me review the system internals.

**Review by likawind — APPROVED** [review]
Great! Appreciate adding the tests!

**Pull request merged**
