### PR TITLE
ENG-2369 Checks List Overview in Check Metadata Table Cell

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR shows check status indicators on one line when the checks metadata table cell is collapsed.

## Related issue number (if any)
ENG-2369

## Loom demo (if any)
https://www.loom.com/share/636740b03f744ea586b38f980e7a7297

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
Great work, @agiron123! A few small things:
1. Can we add some spacing between the icons in the collapsed view?
2. Can we add some spacing between the collapsed view and the "Show Details" text? 
3. I noticed for the workflow titled `warning_bad_check` that we show the workflow as succeeded but then show the check as an error. Shouldn't the check be shown as a ⚠️ icon instead?

**Review by eunice-chan — APPROVED** [review]
Looks good. +1 to the cosmetic things Vikram mentioned. It may also be pretty neat to show a tooltip with the check names on hover of the icons in the contracted state.

**Comment by agiron123** [comment]
> Great work, @agiron123! A few small things:
> 
> 1. Can we add some spacing between the icons in the collapsed view?
> 2. Can we add some spacing between the collapsed view and the "Show Details" text?
> 3. I noticed for the workflow titled `warning_bad_check` that we show the workflow as succeeded but then show the check as an error. Shouldn't the check be shown as a ⚠️ icon instead?

1 & 2: Sure thing, I can work on spacing between the icons and the Show Details text.
3. Good catch, I think this is a bug. I'll look into fixing this up here. If it's too much of a hassle, I can make another linear task and do it there.

**Comment by agiron123** [comment]
> Looks good. +1 to the cosmetic things Vikram mentioned. It may also be pretty neat to show a tooltip with the check names on hover of the icons in the contracted state.

@eunice-chan Good idea here. Let me see what I can do.

**Comment by agiron123** [comment]
@vsreekanti How does this look for spacing?
image

**Comment by agiron123** [comment]
@eunice-chan here is a screenshot of the tooltips:

For preview mode, I've positioned them at the top of the icon as it interferes with the Show Details button. In expanded mode, tooltips will show on the bottom as usual.
image

**Pull request merged**
