### PR TITLE
Moved example training and inference notebook location

### PR DESCRIPTION
**Pull request by cw75**
## Describe your changes and why you are making these changes
Currently the training and inference notebook in the `examples` directory is outdated because we mistakenly put the latest version in `sdk/examples`. This PR moves it to the right location.

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by vsreekanti — APPROVED** [review]

**Comment by jegonzal** [comment]
This is incorrect.  Can we keep both files?  They are different examples.

**Comment by cw75** [comment]
@jegonzal So you want both notebooks in the same directory? What should they be named? Currently they are named roughly the same.

**Comment by cw75** [comment]
@jegonzal bump

**Comment by jegonzal** [comment]
One is more for live presentations and the other is a detailed walk through. Can we name them appropriately and keep both?  @datadawg88 is work some edits to the live presentation version that we will want to merge later this week.

**Comment by vsreekanti** [comment]
@cw75, you can go ahead and merge this, I think.

**Comment by cw75** [comment]
@vsreekanti OK I put Will’s new notebook [here](https://github.com/aqueducthq/aqueduct/tree/move_example_to_right_place/examples/training_and_inference). Now this directory has 3 notebooks. Which one should we deprecate?

**Comment by vsreekanti** [comment]
Keep Will's and the existing version that was in that directory. I'd drop [this one](https://github.com/aqueducthq/aqueduct/blob/move_example_to_right_place/examples/training_and_inference/Live%20Demo%20of%20Training%20and%20Inference.ipynb).

**Pull request merged**
