### PR TITLE
ENG-1880 Hide preview when artifact is cancelled.

### PR DESCRIPTION
**Pull request by agiron123**
## Describe your changes and why you are making these changes
This PR hides artifact previews when the artifact is cancelled.

## Related issue number (if any)
ENG-1880

## Loom demo (if any)
https://www.loom.com/share/a78d9b2a5a71457090a417439cbb619a

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [x] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@agiron123, thanks for this — two things:
1. Can we show a little info alert just saying that the artifact was never created because an upstream operator failed? That way the user knows what they're looking at and why there's no data.
2. The fact that the status is wrong seems like a really big bug. How hard is that fix going to be?

**Comment by agiron123** [comment]
> @agiron123, thanks for this — two things:
> 
> 1. Can we show a little info alert just saying that the artifact was never created because an upstream operator failed? That way the user knows what they're looking at and why there's no data.
> 2. The fact that the status is wrong seems like a really big bug. How hard is that fix going to be?

@vsreekanti 
re: 1: sure, will get an alert added. 

re: 2: In this particular case, the status of the operator doesn't exist. It comes back as undefined, which could be "Unknown" for all we know. I'm not sure why, just going off of what we get in the frontend here. Something we should look into though.

Something else weird I noticed was when I initially set out to do this, I tried starting a workflow and closing my aqueduct server terminal, and the workflow that was running when this happened is stuck in the pending state. I then ran another workflow and let it complete, and I still see a workflow in the pending state in the version selector.

**Comment by agiron123** [comment]
@vsreekanti here's the update alert:

image

**Comment by vsreekanti** [comment]
Looks good! Can you file a task for the other work? I want to make sure we look into it.

**Comment by agiron123** [comment]
> Looks good! Can you file a task for the other work? I want to make sure we look into it.

@vsreekanti Created an issue here: 
https://linear.app/aqueducthq/issue/ENG-2183/artifact-status-set-to-succeeded-when-artifact-failed

**Review by vsreekanti — APPROVED** [review]

**Pull request merged**
