### PR TITLE
Remove system name prefix from newly connected integrations

### PR DESCRIPTION
**Pull request by eunice-chan**
## Describe your changes and why you are making these changes
Remove system prefixes from the integration name because it confuses users

This demo shows two integrations: Snowflake & Postgres. The integration name field has no prefix anymore and upon filling out all the required fields, the confirm button is enabled.

https://user-images.githubusercontent.com/30596854/183711139-926d0625-b098-421d-9ebb-fa21c29f42c7.mov

## Related issue number (if any)
ENG-1252

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [x] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [N/A] If this is a new feature, I have added unit tests and integration tests.
- [N/A] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [x] All features on the UI continue to work correctly.
- [x] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
Thanks @eunice-chan! Just to confirm, once we create the integration, it still doesn't have the prefix, correct?

**Comment by eunice-chan** [comment]
@vsreekanti That's correct. Here is a video of the whole flow creating a snowflake integration:

https://user-images.githubusercontent.com/30596854/183771518-df84b08f-2182-48d5-9648-3f2f043689b1.mov

**Comment by vsreekanti** [comment]
Awesome! Does the integrations page still require a refresh after clicking connect? I could've sworn [this PR](https://github.com/aqueducthq/aqueduct/pull/280) fixed that issue.

**Comment by eunice-chan** [comment]
@vsreekanti It updates automatically :) I refreshed out of force of habit. Here's an updated demo without the refresh:

https://user-images.githubusercontent.com/30596854/183775261-a4a588c7-cca7-4b0e-8f03-221920375bd5.mov

**Comment by vsreekanti** [comment]
Perfect, thanks!

**Review by agiron123 — APPROVED** [review]
LGTM!

**Pull request merged**
