### PR TITLE
[1/3] Adds SourceID field to Workflow.Schedule column

### PR DESCRIPTION
**Pull request by saurav-c**
## Describe your changes and why you are making these changes
This PR adds the `SourceID` field to the `Workflow.Schedule` column. This is necessary to support cascading updates. It also adds a method in the `Workflow` repo to get all target workflows for a given workflow. This is used to perform cascading updates at the end of workflow execution.

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [ ] I have run the integration tests locally and they are passing.
- [ ] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Review by cw75 — COMMENTED** [review]
@saurav-c Is it true that a workflow can only have one trigger type? Say a user configured a workflow to be triggered by another one. But the user may also want to trigger that workflow manually from the UI. Do we support this?

**Comment by saurav-c** [comment]
@cw75 All workflows can be triggered manually regardless of trigger type. This is how the UI works rn.

**Comment by cw75** [comment]
@saurav-c Got it. Another question I had is say I wrote a workflow that runs on Airflow, and want this workflow to be triggered by another workflow. Can I do that? If so what's the trigger type of this workflow?

**Comment by saurav-c** [comment]
@cw75 We currently cannot support cascading updates for Airflow workflows.
1. An Airflow workflow cannot be the source because we cannot trigger new workflow runs at the end of Airflow execution. We will likely never be able to support this.
2.  Currently we cannot support setting a source trigger for an Airflow workflow, because that requires some additional changes to the end of the executor code when all target flows are triggered. I have error checking right now that prevents setting a source trigger for Airflow workflows, but we can remove this once the following task is implemented. I feel like we probably don't need to prioritize this for todays release. https://linear.app/aqueducthq/issue/ENG-2202/enable-providing-a-non-airflow-source-for-an-airflow-workflow

**Comment by cw75** [comment]
@saurav-c got it, is the error checking in another PR? Agreed that we can work on enabling this later after the release.

**Comment by saurav-c** [comment]
@cw75 I just added a commit to #866 to deal with case #2 from above. I had previously forgotten to do so.

**Review by cw75 — APPROVED** [review]

**Comment by likawind** [comment]
LGTM, I think @cw75 's point makes sense that the trigger type can be mixed in future (e.g. both following a schedule or triggered manually). I'm also curious if 'airflow' is a trigger or this information can be captured by engine config. It seems the same argument apply to other self-orchestrated engine?

**Review by likawind — APPROVED** [review]

**Comment by saurav-c** [comment]
@likawind Let me try to clarify a few things and then we can discuss offline if needed.
1. The following trigger types are currently supported (Periodic, Manual, Airflow, Cascading). 
2. Regardless of the the trigger type, you can always trigger a manual run from the SDK of the UI. This applies to Airflow triggers as well.
3. Moving the Airflow trigger type to be part of engine config is more of an internal refactoring task, but agreed we can do it.

**Comment by likawind** [comment]
Thanks for clarifications! Btw this PR is ready for me, I was asking just to learn future plans -

For 1, I somehow mistyped the original question. I'm more curious if 'cascading' and 'scheduled' should be mutually exclusive moving forward? Or a workflow can be triggered by both?

For 3, I'm wondering what 'airflow' trigger means. Does that mean that airflow owns the workflow triggering and we just care about retrieving metadata of already triggered workflows?

**Pull request merged**
