### PR TITLE
Accept both singular and multiple artifacts in publish_flow()

### PR DESCRIPTION
**Pull request by kenxu95**
## Describe your changes and why you are making these changes
Both `client.publish_flow(artifacts=[output])` and `client.publish_flow(artifacts=output)` are possible now. Both arguments cannot be set or else an exception is raised.

Edited the example notebooks to use the singular version where possible.

## Related issue number (if any)
ENG-1735

## Checklist before requesting a review
- [x] I have created a descriptive PR title. The PR title should complete the sentence "This PR...".
- [x] I have performed a self-review of my code.
- [ ] I have included a small demo of the changes. For the UI, this would be a screenshot or a Loom video.
- [ ] If this is a new feature, I have added unit tests and integration tests.
- [x] I have run the integration tests locally and they are passing.
- [x] I have run the linter script locally (See `python3 scripts/run_linters.py -h` for usage).
- [ ] All features on the UI continue to work correctly.
- [ ] Added one of the following CI labels:
    - `run_integration_test`: Runs integration tests
    - `skip_integration_test`: Skips integration tests (Should be used when changes are ONLY documentation/UI)

### CODE REVIEW

**Comment by vsreekanti** [comment]
@kenxu95, I'm concerned that including or dropping the `s` is a subtle difference. Would it make sense to just do `artifacts=output` or `artifacts=[output1, output2]`? That way, it's the same argument with a union-typed value.

**Comment by kenxu95** [comment]
I was concerned [multiple]=[singular] would be confusing, but that does seem like the lesser of two evils. Can fix.

**Comment by vsreekanti** [comment]
I agree. Maybe we should support all combinations? `artifact=[list]`, `artifacts=[list]`, `artifact=obj`, `artifacts=obj`. If a user sets both, we throw an error. Otherwise, we accept either.

**Comment by vsreekanti** [comment]
Maybe that's too complicated...

**Comment by kenxu95** [comment]
yeah that seems like too much tbh

**Comment by kenxu95** [comment]
I wonder if leaving it like this is fine, but we throw a helpful error message if they put the wrong type in?

**Comment by vsreekanti** [comment]
I'd prefer we just accept both under `artifacts`. Generally, if we can predict things that a user might do wrong, we should address those things rather than notify them to do it differently.

**Comment by kenxu95** [comment]
sounds good, this PR was been updated with the change.

**Review by cw75 — APPROVED** [review]
LGTM!

**Pull request merged**
